---
- name: check if satis is installed
  stat: path="{{ satis_installation}}"
  register: satis_installed

- name: install satis
  composer:
    command: "create-project"
    arguments: "composer/satis --stability=dev --keep-vcs"
    working_dir: "{{ satis_installation }}"
  become: yes
  become_user: "{{ satis_user }}"
  when: satis_installed.stat.exists == false

