---
- name: create satis.json
  template:
    src: "satis.json.j2"
    dest: "{{ satis_config_file }}"
  become: yes
  become_user: "{{ satis_user }}"

- name: create build dir
  file:
    owner: "{{ satis_user }}"
    path: "{{ satis_build_dir }}"
    state: directory
    mode: "0733"

- name: build the repository
  command: "{{ satis_installation }}/bin/satis build {{ satis_config_file }} {{ satis_build_dir }}"
  become: yes
  become_user: "{{ satis_user }}"

