---
- name: create satis.json
  template:
    src: "satis.json.j2"
    dest: "{{ satis_config_file }}"
  become: yes
  become_user: "{{ satis_user }}"
  register: satis_config_file_created

- name: create build dir
  file:
    owner: "{{ satis_user }}"
    path: "{{ satis_build_dir }}"
    state: directory
    mode: "0733"

- name: count number of files in {{ satis_build_dir }}
  find:
    paths: "{{ satis_build_dir }}"
  register: find_satis_build_dir

- name: build the repository
  command: "{{ satis_installation }}/bin/satis build {{ satis_config_file }} {{ satis_build_dir }}"
  become: yes
  become_user: "{{ satis_user }}"
  when: satis_config_file_created.changed == true or find_satis_build_dir.matched == 0
